"""empty message

Revision ID: 409836b7866e
Revises: a40e2cc1ae2
Create Date: 2016-06-19 04:46:44.569336

"""

# revision identifiers, used by Alembic.
revision = '409836b7866e'
down_revision = 'a40e2cc1ae2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('profile_url', table_name='users')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('profile_url', 'users', ['profile_url'], unique=True)
    ### end Alembic commands ###
